### ISSUE TITLE
Error communicating with device

### ISSUE THREAD

**Issue by koldogut** [SLaweck/homebridge-tuya-smartlamp#2]
Since just a few weeks ago Im getting this error all the time "[TA] retryable in getSchemaRetryable get schema error: Error communicating with device. Make sure nothing else is trying to control it or connected to it." for all the devices defined in the config (4 SmartPlugs) ¿Any ideas?

**Comment by displaced** [comment]
I've just been playing with this plugin and see the same error (although I only get `[TA] retryable in getSchemaRetryable get schema error: undefined` - not the rest of the message).

Additionally, control of my smart lights is very flaky.  There's lots of lag, and it doesn't always do what it's supposed to.

I'm going to switch to the official `homebridge-tuya` to see if I can at least get reliable on/off and dimming.  I'll leave colour and colour-temperature changing to Alexa

**Comment by gazzmanzx6** [comment]
I've just tried this plugin and get a similar error that causes Homebridge to hang.
[Socket] [TA] Socket resolve IP error
I have 3 sockets connected and all 3 were giving this error.
I've also had to go back to homebridge-tuya which seems to work ok but doesn't give the power usage in EveHome app.
Is there a way to specify a fixed IP address in this plugin?

**Comment by xatrix78** [comment]
Yes I have the same Problem as @gazzmanzx6

**Comment by xatrix78** [comment]
I specify the IP and Name in my Router, so there is no Problem to resolv the ip. But I get the getSchemaRetryable get schema error: undefined Error. I think it is a Problem with the Power. The Plugs are working but the Power counter are not.

**Comment by SLaweck** [comment]
Hi, I've just upgrade TuyAPI lib and switched code to use permanent connection. This should eliminate lags and other problems.
Cheers
