### ISSUE TITLE
Smart Socket SP21 

### ISSUE THREAD

**Issue by vinacc** [SLaweck/homebridge-tuya-smartlamp#6]
Hi, I just installed your plugin on my raspberry pi3 + with homebridge.

Homekit detects my two SP21 Teckin sockets but they turn off and I can't turn them on or off.

Am I wrong? This is the configuration I used.

```
"accessories": [
{
"accessory": "TuyaSmartDevice",
"name": "TV",
"type": "outlet",
"manufacturer": "Teckin",
"model": "Smart Socket SP21",
"devId": “myID1",
"localKey": “myKey1",
"interval": 15
},
{
"accessory": "TuyaSmartDevice",
"name": "Bagno",
"type": "outlet",
"manufacturer": "Teckin",
"model": "Smart Socket SP21",
"devId": "myID2",
"localKey": "myKey2",
"interval": 15
}
]
```

This is the homebridge log:

> [9/22/2019, 2:17:25 PM] [TV] Initializing TuyaSmartDevice accessory...
> [9/22/2019, 2:17:25 PM] [Bagno] Initializing TuyaSmartDevice accessory...
> [9/22/2019, 2:18:49 PM] [TV] IP address resolved 192.168.1.68 [TO]
> [9/22/2019, 2:18:49 PM] [Bagno] IP address resolved 192.168.1.194 [TO]
> [9/22/2019, 2:18:51 PM] [TV] Connection problem - force device disconnect [TO]
> [9/22/2019, 2:18:51 PM] [Bagno] Connection problem - force device disconnect [TO]

Regards,
Vincenzo

**Comment by aplr** [comment]
Just add `"version": "3.3"` to each accessory and it should work, at least it did for me!

**Comment by vinacc** [comment]
Works. Thanks
