### ISSUE TITLE
LED Smart Bulb SB50

### ISSUE THREAD

**Issue by vinacc** [SLaweck/homebridge-tuya-smartlamp#9]
Hi, I just installed your plugin on my raspberry pi3 + with homebridge.

Homekit detects my two SB50 (Smart Bulb) Teckin but they turn off and I can't turn them on or off.

Am I wrong? This is the configuration I used.
 

`{
            "accessory": "TuyaSmartDevice",
            "name": "Luce cucina",
            "type": "lightbulb dimmable tunable color",
            "manufacturer": "Teckin",
            "model": "Smart Lamp Multicolor",
            "devId": "363416362cf43255c507",
            "localKey": "21dfcf8ce71f16cc",
            "version": "3.3",
            "enableColor": true
        },
        {
            "accessory": "TuyaSmartDevice",
            "name": "Luce camera da letto",
            "type": "lightbulb dimmable tunable color",
            "manufacturer": "Teckin",
            "model": "Smart Lamp Multicolor",
            "devId": "363416364c11ae09891d",
            "localKey": "7194b2560ae83846",
            "version": "3.3",
            "enableColor": true
        }
`

**Comment by SLaweck** [comment]
Hi
Please try with "version": "3.1".

**Comment by LeonCloud** [comment]
I'm trying too but nothing (Same SB50 Teckin Bulb).
{
    "accessory": "TuyaSmartDevice",
    "name": "Luce Scrivania",
    "type": "lightbulb dimmable tunable color",
    "manufacturer": "Teckin",
    "model": "Smart Lamp Multicolor",
    "devId": "5317500710521cf34743",
    "localKey": "4bfbc2032975a49d",
    "enableColor": true,
    "version": "3.1"
}

And in Log:
14/10/2020, 18:17:30 [Luce Scrivania] IP address resolved 192.168.1.74 [TLB]
14/10/2020, 18:17:30 [Luce Scrivania] IP address resolved 192.168.1.74 [TLB]
14/10/2020, 18:17:30 [Luce Principale] IP address resolved 192.168.1.191 [TLB]
14/10/2020, 18:17:30 [Luce Principale] IP address resolved 192.168.1.191 [TLB]
14/10/2020, 18:17:30 [Luce Principale] IP address resolved 192.168.1.191 [TLB]
14/10/2020, 18:17:30 [Luce Principale] IP address resolved 192.168.1.191 [TLB]
14/10/2020, 18:17:30 [Luce Principale] IP address resolved 192.168.1.191 [TLB]
14/10/2020, 18:17:30 [Luce Scrivania] Device connected [TLB]
14/10/2020, 18:17:30 [Luce Principale] Device connected [TLB]
14/10/2020, 18:17:31 [Luce Principale] Device connected [TLB]
14/10/2020, 18:17:31 [Luce Scrivania] Device connected [TLB]
14/10/2020, 18:17:31 [Luce Principale] Device connected [TLB]
14/10/2020, 18:17:33 [Luce Scrivania] Device connected [TLB]
14/10/2020, 18:17:34 [Luce Principale] Device connected [TLB]
14/10/2020, 18:17:38 [Luce Scrivania] Connection problem - force device disconnect [TLB]

What do you think? Is possibile to fix?

Thank you so much guys !

**Comment by stackk1** [comment]
Same Issue here, tried with both version numbers

**Comment by TrafalgaT** [comment]
has anyone been able to figure this out ? i am also having this issue that i just cant map this device ( LED Smart Bulb SB60 in my case). I have tried two plugins sofar, homebridge-tuya and this one and neither work

**Comment by Nachtmeer** [comment]
Is there a solution for this?
